version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - 3000:3000
    depends_on: ["db"]
    profiles: ["prod"]

  db:
    image: surrealdb/surrealdb:latest
    env_file:
      - path: ./.env
        required: true
    entrypoint: 
      - /surreal 
      - start
      - --auth
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
      - --allow-all
    ports:
      - 8000:8000
    profiles: ["dev", "prod"]