services:
  db:
    image: surrealdb/surrealdb:v2.0
    user: root
    entrypoint: 
      - /surreal
      - start
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
      - --allow-all
      - rocksdb:database.db
    healthcheck:
      test: ["CMD", "/surreal", "isready"]
      interval: 1m
      start_interval: 4s
      start_period: 10s

  migrate:
    image: surrealdb/surrealdb:v2.0
    entrypoint:
      - /surreal
      - import
      - --endpoint
      - http://db:8000
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
      - --ns
      - $DB_NAMESPACE
      - --db
      - playground
      - /extras/schema.surql
    # Commented out because it causes the db container to be recreated
    # depends_on:
    #   db:
    #     condition: service_healthy
    volumes:
      - ./tools/schema.surql:/extras/schema.surql:ro

  sql:
    image: surrealdb/surrealdb:v2.0
    entrypoint:
      - /surreal
      - sql
      - --endpoint
      - http://db:8000
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
      - --ns
      - $DB_NAMESPACE
      - --db
      - playground
    # Commented out because it causes the db container to be recreated
    # depends_on:
    #   db:
    #     condition: service_healthy