services:
  app:
    image: cosmtrek/air
    working_dir: /app
    ports:
      - ${BACKEND_PORT}:3000
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy
    env_file: .env

  db:
    extends:
      file: compose.base.yml
      service: db
    ports:
      - "8000:8000"