services:
  db:
    image: surrealdb/surrealdb:v2.1.4
    user: root
    entrypoint:
      - /surreal
      - start
      - --import-file
      - /extras/schema.surql
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
      - --allow-all
      - rocksdb:/database.db
    healthcheck:
      test: ["CMD", "/surreal", "isready"]
      interval: 1m
      start_interval: 4s
      start_period: 10s
    volumes:
      - ./tools/schema.surql:/extras/schema.surql:ro

  migrate:
    image: surrealdb/surrealdb:v2.1.4
    entrypoint:
      - /surreal
      - import
      - --endpoint
      - http://db:8000
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
      - --ns
      - lex
      - --db
      - playground
      - /extras/schema.surql
    volumes:
      - ./tools/schema.surql:/extras/schema.surql:ro

  sql:
    image: surrealdb/surrealdb:v2.1.4
    entrypoint:
      - /surreal
      - sql
      - --endpoint
      - http://db:8000
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
      - --ns
      - lex
      - --db
      - playground
