version: '3'

services:
  app:
    image: cosmtrek/air
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy
    env_file: .env

  migrate:
    extends:
      file: compose.base.yml
      service: migrate
    depends_on:
      db:
        condition: service_healthy

  db:
    extends:
      file: compose.base.yml
      service: db
    ports:
      - "8000:8000"