services:
  app:
    build:
      context: .
      dockerfile: Containerfile
    env_file: .env
    environment:
      # Set defaults and specify variables here for coolify to pick up
      - 'SURREAL_USER=${SURREAL_USER:-root}'
      - 'SURREAL_PASS=${SURREAL_PASS:-root}'
      - 'BACKEND_PORT=${BACKEND_PORT:-3000}'
    ports:
        - ${BACKEND_PORT}:3000
    depends_on:
      db:
        condition: service_healthy

  db:
    extends:
      file: compose.base.yml
      service: db
    volumes:
      - database:/database.db

volumes:
  database: