services:
  app:
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - ${BACKEND_PORT}:3000
    depends_on:
      db:
        condition: service_healthy
    env_file: .env

  db:
    extends:
      file: compose.base.yml
      service: db
    ports:
      - ${DATABASE_PORT}:8000
    volumes:
      - database:/database.db
    env_file: .env

volumes:
  database: