services:
  test:
    build:
      context: .
      dockerfile: ./test/Containerfile
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy
    env_file: .env.testing
  
  db:
    extends:
      file: compose.base.yml
      service: db