services:
  db:
    image: surrealdb/surrealdb:v2.1.4
    user: root
    ports:
      - ${DATABASE_PORT}:8000
    entrypoint:
      - /surreal
      - start
      - --import-file
      - /extras/schema.surql
      - --allow-all
      - rocksdb:/database.db
    healthcheck:
      test: 
        - CMD
        - /surreal
        - isready
      interval: 1m
      start_interval: 4s
      start_period: 10s
    volumes:
      - ./tools/schema.surql:/extras/schema.surql:ro
      - ./lex_db:/database.db
    env_file: .env
  
  migrate:
    image: surrealdb/surrealdb:v2.1.4
    entrypoint:
      - /surreal
      - import
      - --endpoint
      - http://db:8000
      - --ns
      - lex
      - --db
      - playground
      - /extras/schema.surql
    volumes:
      - ./tools/schema.surql:/extras/schema.surql:ro
    env_file: .env
    profiles: [debug]

  
  sql:
    image: surrealdb/surrealdb:v2.1.4
    entrypoint:
      - /surreal
      - sql
      - --endpoint
      - http://db:8000
      - --ns
      - lex
      - --db
      - playground
    env_file: .env
    profiles: [debug]
  
  dev:
    image: cosmtrek/air
    working_dir: /app
    ports:
      - ${BACKEND_PORT}:3000
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    profiles: [dev]

  app:
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - ${BACKEND_PORT}:3000
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    profiles: [prod]
