services:
  app:
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy

  db:
    extends:
      file: compose.base.yml
      service: db