version: '3'

services:
  app:
    build:
      dockerfile: Containerfile.dev
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      
  db:
    extends:
      file: compose.base.yml
      service: db
    ports:
      - "8000:8000"