services:
  app:
    build:
      context: .
      dockerfile: Containerfile
    environment:
      # Set defaults and specify variables here for coolify to pick up
      - 'SURREAL_USER=${SERVICE_USER_DB}'
      - 'SURREAL_PASS=${SERVICE_PASSWORD_DB}'
      - 'PUBLIC_URI=${PUBLIC_URI:-https://lex.local.crux-bphc.com}'
      - 'CORS_ORIGINS=${CORS_ORIGINS:-*}'
    depends_on:
      db:
        condition: service_healthy

  db:
    extends:
      file: compose.base.yml
      service: db
    environment:
      - 'SURREAL_USER=${SERVICE_USER_DB}'
      - 'SURREAL_PASS=${SERVICE_PASSWORD_DB}'
    volumes:
      - database:/database.db

volumes:
  database: