services:
  app:
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - ${BACKEND_PORT:-3000}:3000
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    env_file: .env

  migrate:
    extends:
      file: compose.base.yml
      service: migrate
    depends_on:
      db:
        condition: service_healthy

  db:
    extends:
      file: compose.base.yml
      service: db
    volumes:
      - type: bind
        source: ./store/database.db
        target: /database.db
        is_directory: true

